services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: example-postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: example-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "testuser",
          "-ptestpass",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: example-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
      MONGO_INITDB_DATABASE: testdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init.js
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    container_name: example-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MinIO Client - Create bucket and setup
  minio-setup:
    image: minio/mc:latest
    container_name: example-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      mc mb myminio/backup-bucket --ignore-existing;
      mc anonymous set public myminio/backup-bucket;
      echo 'MinIO setup complete';
      "

  # Data Generator - Inserts random data into PostgreSQL
  postgres-data-generator:
    image: postgres:15-alpine
    container_name: example-postgres-data-generator
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: testdb
      PGUSER: testuser
      PGPASSWORD: testpass
    volumes:
      - ./generate-data.sh:/generate-data.sh
    command: >
      /bin/sh -c "
      chmod +x /generate-data.sh;
      while true; do
        /generate-data.sh;
        sleep 30;
      done
      "

  # MySQL Data Generator - Inserts random data into MySQL
  mysql-data-generator:
    image: mysql:8.0
    container_name: example-mysql-data-generator
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - ./generate-mysql-data.sh:/generate-mysql-data.sh
    command: >
      /bin/sh -c "
      chmod +x /generate-mysql-data.sh;
      while true; do
        /generate-mysql-data.sh;
        sleep 30;
      done
      "

  # MongoDB Data Generator - Inserts random data into MongoDB
  mongodb-data-generator:
    image: mongo:7.0
    container_name: example-mongodb-data-generator
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: testdb
      MONGO_USER: testuser
      MONGO_PASSWORD: testpass
    volumes:
      - ./generate-mongo-data.sh:/generate-mongo-data.sh
    command: >
      /bin/sh -c "
      chmod +x /generate-mongo-data.sh;
      while true; do
        /generate-mongo-data.sh;
        sleep 30;
      done
      "

  # Easy Backup Service
  easy-backup:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: example-easy-backup
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./backup-config.yaml:/app/config.yaml
    ports:
      - "8080:8080"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
  mysql_data:
  mongodb_data:
  minio_data:

networks:
  default:
    name: easy-backup-network
